### PR TITLE
Extend Generic instance for type constructors (#11)

### LINKED ISSUE #11: Generic instances for type constructors wrong?
As @akegalj pointed out:

https://github.com/eskimor/purescript-bridge/blob/master/src/Language/PureScript/Bridge/Printer.hs#L77

The derive Generic instance only covers the typename, but it should also include type parameters:

```purescript
data Foo a = Foo Int

derive instance genericFoo :: Generic (Foo a) 
```

instead of just

```purescript
derive instance genericFoo :: Generic Foo
```

### PR DESCRIPTION
**Pull request by akegalj**
Should fix #11.

### CODE REVIEW

**Comment by akegalj** [comment]
Sorry for these 3 commits. If you don't like it I will squash it into one commit.

File: src/Language/PureScript/Bridge/Printer.hs [hunk 1]
```diff
@@ -71,10 +71,24 @@ importLineToText l = "import " <> importModule l <> " (" <> typeList <> ")"
...
+        | otherwise = (<> " => ") $
+            if stpLength == 1
+                then genericConstrainsInner
+                else bracketWrap genericConstrainsInner
+    genericConstrainsInner = T.intercalate ", " $ map genericInstance sumTypeParameters
+    stpLength = length sumTypeParameters
+    bracketWrap x = "(" <> x <> ")"
+    sumTypeParameters = filter isTypeParameter $ getUsedTypes st
+    -- TODO: I find this stupid. Would much rather like some other way to make this check?
+    isTypeParameter tp = T.toLower (_typeName tp) == _typeName tp
```
Comment (eskimor) [inline src/Language/PureScript/Bridge/Printer.hs]: Just filter used types by whether they are contained in the sumtype's TypeInfo's `_typeParameters`.

Comment (akegalj) [inline src/Language/PureScript/Bridge/Printer.hs]: Ah, I see. Will update this in a min
Dana 6. 9. 2016. 10:43 "Robert Klotzner" <notifications@github.com> je
napisao/la:
>
> In src/Language/PureScript/Bridge/Printer.hs:
>
> > -  : [ "\nderive instance generic" <> _typeName t <> " :: Generic " <>
_typeName t ]
> > +  : [ "\nderive instance generic" <> _typeName t <> " :: " <>
genericConstrains <> genericInstance t ]
> > +  where
> > +    genericInstance = ("Generic " <>) . typeInfoToText False
> > +    genericConstrains
> > +        | stpLength == 0 = mempty
> > +        | otherwise = (<> " => ") $
> > +            if stpLength == 1
> > +                then genericConstrainsInner
> > +                else bracketWrap genericConstrainsInner
> > +    genericConstrainsInner = T.intercalate ", " $ map genericInstance
sumTypeParameters
> > +    stpLength = length sumTypeParameters
> > +    bracketWrap x = "(" <> x <> ")"
> > +    sumTypeParameters = filter isTypeParameter $ getUsedTypes st
> > +    -- TODO: I find this stupid. Would much rather like some other way
to make this check?
> > +    isTypeParameter tp = T.toLower (_typeName tp) == _typeName tp
>
> Just filter used types by whether they are contained in the sumtype's
TypeInfo's _typeParameters.

Comment (eskimor) [inline src/Language/PureScript/Bridge/Printer.hs]: which is t ^. typeParameters, something like:

```haskell
sumTypeParameters = filter (`elem` getUsedTypes st) $ t ^. typeParameters
```

I just noticed from the definition of `getUsedTypes` that it preserves duplicates - so filtering `t ^. typeParameters` is correct, the other way round could result in instances like:

```purescript
instance genericFoo :: (Generic a, Generic a, Generic a) => Generic (Foo a)
```
Obviously it might be bad that getUsedTypes does not filter duplicates - I am going to check, at least it should be documented.

**Comment by eskimor** [comment]
I don't care about multiple commits. Also I like your coding style :-)

**Comment by eskimor** [comment]
Yeah -the not filtering of duplicates did not matter, because it was only used for constructing maps and sets.

**Comment by akegalj** [comment]
Should we then filter out duplicates in `getUsedTypes` ? (I don't think it make sense to leave duplicates there)

**Comment by eskimor** [comment]
I am currently thinking about this. It does not make sense, but if we drop duplicates we should probably return a `Set` not a `List`.

**Comment by eskimor** [comment]
I am on it. It is going to be a set.

**Comment by eskimor** [comment]
Fix is in master

**Comment by akegalj** [comment]
Thanks. I am going to update this PR.

File: src/Language/PureScript/Bridge/Printer.hs [hunk 2]
```diff
@@ -83,9 +83,9 @@ sumTypeToText st@(SumType t cs) = T.unlines $
     genericConstrainsInner = T.intercalate ", " $ map genericInstance sumTypeParameters
     stpLength = length sumTypeParameters
     bracketWrap x = "(" <> x <> ")"
-    sumTypeParameters = filter isTypeParameter $ getUsedTypes st
-    -- TODO: I find this stupid. Would much rather like some other way to make this check?
-    isTypeParameter tp = T.toLower (_typeName tp) == _typeName tp
+    sumTypeParameters = filter isTypeParam . Set.toList $ getUsedTypes st
+    -- NOTE: only this captures monadic type parameters. See test/Spec.hs
+    isTypeParam typ = T.toLower (_typeName typ) == _typeName typ
```
Comment (akegalj) [inline src/Language/PureScript/Bridge/Printer.hs]: Please see `test/Spec` for it. Solution that you have proposed doesn't cover this case:
```
data Bar2 a b m =
    Bar1 (Maybe a)
  | Bar2 (Either a b)
  | Bar3 a
  | Bar4 {
      myMonadicResult :: m b
    }

derive instance genericBar2 :: (Generic a, Generic b, Generic (m b)) => Generic (Bar2 a b m)  
```
If you have some other way to handle this case, please comment. I don't know how to properly handle monadic type parameters except this way, which I don't like

Comment (eskimor) [inline src/Language/PureScript/Bridge/Printer.hs]: You are right! But it should work if you don't compare the full TypeInfo's but only their `_typeName`. This would cover your case. The used types contain a TypeInfo named m (with type parameter b - which is fine) and b itself - both would be found and contained in the constraints.

Comment (eskimor) [inline src/Language/PureScript/Bridge/Printer.hs]: Oh -you are already doing that :-P

Comment (akegalj) [inline src/Language/PureScript/Bridge/Printer.hs]: you are right, let me fix it.

Comment (akegalj) [inline src/Language/PureScript/Bridge/Printer.hs]: Its done in https://github.com/eskimor/purescript-bridge/pull/12/commits/0f3ca880c2949908b776fabf2bdbc11628878a02
